// <auto-generated />
using System;
using Guardias.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Guardias.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519191445_AddPasswordPlain")]
    partial class AddPasswordPlain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Guardias.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EdificioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EdificioId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Guardias.Models.AreaRonda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<bool>("Completada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RondaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("RondaId");

                    b.ToTable("AreaRondas");
                });

            modelBuilder.Entity("Guardias.Models.Edificio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Edificios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Torre principal - lobby y accesos",
                            Nombre = "Torre A"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Torre secundaria - oficinas",
                            Nombre = "Torre B"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Planta subterranea y accesos vehiculares",
                            Nombre = "Estacionamiento"
                        });
                });

            modelBuilder.Entity("Guardias.Models.FotoRonda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaRondaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCaptura")
                        .HasColumnType("datetime2");

                    b.Property<string>("RutaFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaRondaId");

                    b.ToTable("FotosRonda");
                });

            modelBuilder.Entity("Guardias.Models.Guardia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EdificioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EdificioId");

                    b.ToTable("Guardias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Cargo = "Guardia",
                            EdificioId = 1,
                            Nombre = "Carlos Ramirez",
                            Turno = 0
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Cargo = "Supervisora",
                            EdificioId = 1,
                            Nombre = "Ana Martinez",
                            Turno = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Cargo = "Guardia",
                            EdificioId = 2,
                            Nombre = "Luis Gonzalez",
                            Turno = 2
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Cargo = "Guardia",
                            EdificioId = 3,
                            Nombre = "Sofia Herrera",
                            Turno = 0
                        });
                });

            modelBuilder.Entity("Guardias.Models.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotasCierre")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RondaId")
                        .HasColumnType("int");

                    b.Property<int>("Severidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RondaId");

                    b.ToTable("Incidencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Puerta de emergencia piso 3 no cierra.",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 5, 7, 14, 25, 0, 0, DateTimeKind.Unspecified),
                            RondaId = 2,
                            Severidad = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Camara del pasillo B sin senal.",
                            Estado = 0,
                            FechaCreacion = new DateTime(2026, 5, 7, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            RondaId = 3,
                            Severidad = 2
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Extintor vencido piso 2 Torre A.",
                            Estado = 2,
                            FechaCierre = new DateTime(2026, 5, 7, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaCreacion = new DateTime(2026, 5, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            NotasCierre = "Extintor reemplazado.",
                            RondaId = 1,
                            Severidad = 0
                        });
                });

            modelBuilder.Entity("Guardias.Models.Ronda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EdificioId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFirma")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GuardiaId")
                        .HasColumnType("int");

                    b.Property<string>("ReporteIncidencias")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EdificioId");

                    b.HasIndex("GuardiaId");

                    b.ToTable("Rondas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EdificioId = 1,
                            Estado = 2,
                            FechaFirma = new DateTime(2026, 5, 7, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            FechaHora = new DateTime(2026, 5, 7, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            FirmadoPor = "Ana Martinez",
                            GuardiaId = 1
                        },
                        new
                        {
                            Id = 2,
                            EdificioId = 2,
                            Estado = 1,
                            FechaHora = new DateTime(2026, 5, 7, 14, 10, 0, 0, DateTimeKind.Unspecified),
                            GuardiaId = 2
                        },
                        new
                        {
                            Id = 3,
                            EdificioId = 2,
                            Estado = 1,
                            FechaHora = new DateTime(2026, 5, 7, 22, 5, 0, 0, DateTimeKind.Unspecified),
                            GuardiaId = 3
                        },
                        new
                        {
                            Id = 4,
                            EdificioId = 3,
                            Estado = 0,
                            FechaHora = new DateTime(2026, 5, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            GuardiaId = 4
                        },
                        new
                        {
                            Id = 5,
                            EdificioId = 1,
                            Estado = 1,
                            FechaHora = new DateTime(2026, 5, 8, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            GuardiaId = 1
                        });
                });

            modelBuilder.Entity("Guardias.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EdificioId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuardiaId")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("HoraProgramada")
                        .HasColumnType("time");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EdificioId");

                    b.HasIndex("GuardiaId");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Revisar estado y vencimiento de extintores.",
                            EdificioId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraProgramada = new TimeOnly(8, 0, 0),
                            Titulo = "Verificar extintores",
                            Turno = 0
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Verificar barreras y accesos del estacionamiento.",
                            EdificioId = 3,
                            Estado = 0,
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraProgramada = new TimeOnly(7, 30, 0),
                            Titulo = "Ronda estacionamiento",
                            Turno = 3
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Comprobar que las camaras esten operativas.",
                            EdificioId = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraProgramada = new TimeOnly(14, 0, 0),
                            Titulo = "Revisar camaras",
                            Turno = 1
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Registrar entradas y salidas entre 22:00 y 06:00.",
                            EdificioId = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuardiaId = 3,
                            HoraProgramada = new TimeOnly(22, 0, 0),
                            Titulo = "Control acceso nocturno",
                            Turno = 2
                        });
                });

            modelBuilder.Entity("Guardias.Models.UsuarioEdificio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("EdificioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordPlain")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EdificioId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("UsuariosEdificio");
                });

            modelBuilder.Entity("Guardias.Models.Area", b =>
                {
                    b.HasOne("Guardias.Models.Edificio", "Edificio")
                        .WithMany("Areas")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edificio");
                });

            modelBuilder.Entity("Guardias.Models.AreaRonda", b =>
                {
                    b.HasOne("Guardias.Models.Area", "Area")
                        .WithMany("AreaRondas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Guardias.Models.Ronda", "Ronda")
                        .WithMany("AreaRondas")
                        .HasForeignKey("RondaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Ronda");
                });

            modelBuilder.Entity("Guardias.Models.FotoRonda", b =>
                {
                    b.HasOne("Guardias.Models.AreaRonda", "AreaRonda")
                        .WithMany("Fotos")
                        .HasForeignKey("AreaRondaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaRonda");
                });

            modelBuilder.Entity("Guardias.Models.Guardia", b =>
                {
                    b.HasOne("Guardias.Models.Edificio", "Edificio")
                        .WithMany("Guardias")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Edificio");
                });

            modelBuilder.Entity("Guardias.Models.Incidencia", b =>
                {
                    b.HasOne("Guardias.Models.Ronda", "Ronda")
                        .WithMany("Incidencias")
                        .HasForeignKey("RondaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ronda");
                });

            modelBuilder.Entity("Guardias.Models.Ronda", b =>
                {
                    b.HasOne("Guardias.Models.Edificio", "Edificio")
                        .WithMany("Rondas")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Guardias.Models.Guardia", "Guardia")
                        .WithMany("Rondas")
                        .HasForeignKey("GuardiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Edificio");

                    b.Navigation("Guardia");
                });

            modelBuilder.Entity("Guardias.Models.Tarea", b =>
                {
                    b.HasOne("Guardias.Models.Edificio", "Edificio")
                        .WithMany("Tareas")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Guardias.Models.Guardia", "Guardia")
                        .WithMany("Tareas")
                        .HasForeignKey("GuardiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Edificio");

                    b.Navigation("Guardia");
                });

            modelBuilder.Entity("Guardias.Models.UsuarioEdificio", b =>
                {
                    b.HasOne("Guardias.Models.Edificio", "Edificio")
                        .WithMany("UsuariosEdificio")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edificio");
                });

            modelBuilder.Entity("Guardias.Models.Area", b =>
                {
                    b.Navigation("AreaRondas");
                });

            modelBuilder.Entity("Guardias.Models.AreaRonda", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Guardias.Models.Edificio", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Guardias");

                    b.Navigation("Rondas");

                    b.Navigation("Tareas");

                    b.Navigation("UsuariosEdificio");
                });

            modelBuilder.Entity("Guardias.Models.Guardia", b =>
                {
                    b.Navigation("Rondas");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Guardias.Models.Ronda", b =>
                {
                    b.Navigation("AreaRondas");

                    b.Navigation("Incidencias");
                });
#pragma warning restore 612, 618
        }
    }
}
