// <auto-generated />
using System;
using Guardias.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Guardias.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520161257_AddNombreOperador")]
    partial class AddNombreOperador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Guardias.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EdificioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EdificioId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Guardias.Models.AreaRonda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<bool>("Completada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RondaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("RondaId");

                    b.ToTable("AreaRondas");
                });

            modelBuilder.Entity("Guardias.Models.Edificio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Edificios");
                });

            modelBuilder.Entity("Guardias.Models.FotoRonda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaRondaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCaptura")
                        .HasColumnType("datetime2");

                    b.Property<string>("RutaFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaRondaId");

                    b.ToTable("FotosRonda");
                });

            modelBuilder.Entity("Guardias.Models.Guardia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EdificioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EdificioId");

                    b.ToTable("Guardias");
                });

            modelBuilder.Entity("Guardias.Models.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotasCierre")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RondaId")
                        .HasColumnType("int");

                    b.Property<int>("Severidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RondaId");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("Guardias.Models.Ronda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EdificioId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFirma")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GuardiaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreOperador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReporteIncidencias")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EdificioId");

                    b.HasIndex("GuardiaId");

                    b.ToTable("Rondas");
                });

            modelBuilder.Entity("Guardias.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EdificioId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuardiaId")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("HoraProgramada")
                        .HasColumnType("time");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EdificioId");

                    b.HasIndex("GuardiaId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("Guardias.Models.UsuarioEdificio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("EdificioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordPlain")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EdificioId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("UsuariosEdificio");
                });

            modelBuilder.Entity("Guardias.Models.Area", b =>
                {
                    b.HasOne("Guardias.Models.Edificio", "Edificio")
                        .WithMany("Areas")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edificio");
                });

            modelBuilder.Entity("Guardias.Models.AreaRonda", b =>
                {
                    b.HasOne("Guardias.Models.Area", "Area")
                        .WithMany("AreaRondas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Guardias.Models.Ronda", "Ronda")
                        .WithMany("AreaRondas")
                        .HasForeignKey("RondaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Ronda");
                });

            modelBuilder.Entity("Guardias.Models.FotoRonda", b =>
                {
                    b.HasOne("Guardias.Models.AreaRonda", "AreaRonda")
                        .WithMany("Fotos")
                        .HasForeignKey("AreaRondaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaRonda");
                });

            modelBuilder.Entity("Guardias.Models.Guardia", b =>
                {
                    b.HasOne("Guardias.Models.Edificio", "Edificio")
                        .WithMany("Guardias")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Edificio");
                });

            modelBuilder.Entity("Guardias.Models.Incidencia", b =>
                {
                    b.HasOne("Guardias.Models.Ronda", "Ronda")
                        .WithMany("Incidencias")
                        .HasForeignKey("RondaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ronda");
                });

            modelBuilder.Entity("Guardias.Models.Ronda", b =>
                {
                    b.HasOne("Guardias.Models.Edificio", "Edificio")
                        .WithMany("Rondas")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Guardias.Models.Guardia", "Guardia")
                        .WithMany("Rondas")
                        .HasForeignKey("GuardiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Edificio");

                    b.Navigation("Guardia");
                });

            modelBuilder.Entity("Guardias.Models.Tarea", b =>
                {
                    b.HasOne("Guardias.Models.Edificio", "Edificio")
                        .WithMany("Tareas")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Guardias.Models.Guardia", "Guardia")
                        .WithMany("Tareas")
                        .HasForeignKey("GuardiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Edificio");

                    b.Navigation("Guardia");
                });

            modelBuilder.Entity("Guardias.Models.UsuarioEdificio", b =>
                {
                    b.HasOne("Guardias.Models.Edificio", "Edificio")
                        .WithMany("UsuariosEdificio")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edificio");
                });

            modelBuilder.Entity("Guardias.Models.Area", b =>
                {
                    b.Navigation("AreaRondas");
                });

            modelBuilder.Entity("Guardias.Models.AreaRonda", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Guardias.Models.Edificio", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Guardias");

                    b.Navigation("Rondas");

                    b.Navigation("Tareas");

                    b.Navigation("UsuariosEdificio");
                });

            modelBuilder.Entity("Guardias.Models.Guardia", b =>
                {
                    b.Navigation("Rondas");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Guardias.Models.Ronda", b =>
                {
                    b.Navigation("AreaRondas");

                    b.Navigation("Incidencias");
                });
#pragma warning restore 612, 618
        }
    }
}
